### PR TITLE
Add fields

### PR DESCRIPTION
**Pull request by petski**
Add fields: ```Attachments.FriendlyContentLength```, ```Transaction.Content```, ```Attachments.*```.

I'm trying to create feature parity for ```/REST/1.0/ticket/:id/history?format=l``` in REST 2.0 (but with TxnCustomFields added). With this patch installed, I succeed to do so with the following URL:

 ```/REST/2.0/ticket/:id/history?fields=id,Type,Creator,Created,CustomFields,Content,Attachments&fields[CustomFields]=Name,Values&fields[Attachments]=ContentType,Filename,FriendlyContentLength```

Please let me know your thoughts.

### CODE REVIEW

**Comment by puck** [comment]
Fantastic!

I've cherry-picked this commit onto this branch: https://github.com/catalyst-cloud/rt-extension-rest2/tree/search-fields-groups

What would be wonderful to see is some test cases which exercise these new fields.

Cheers,
Andrew

**Comment by puck** [comment]
Hey @sunnavy you might be interested in this PR as well. I haven't looked into the test cases for this yet, and @petski doesn't appear to have added any to his branch.

**Comment by sunnavy** [comment]
@puck I can take a look at it a bit later, and it'll be great if you can create a PR to our repo for it.

Thanks!

**Comment by petski** [comment]
"Copied" PR to https://github.com/bestpractical/rt-extension-rest2/pull/39. Will close here and will welcome you to continue this thread on the new location.

**Pull request closed without merging**
